# Generated by Django 4.2.3 on 2024-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoicedetail_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_name', models.TextField(default='')),
                ('total_amt', models.FloatField(default=0)),
                ('amount_payable', models.FloatField(default=0)),
                ('amount_paid', models.FloatField(default=0)),
                ('balance_amt', models.FloatField(default=0)),
            ],
        ),
    ]
