# Generated by Django 4.2.3 on 2024-01-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_purchase_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_details',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice'),
        ),
    ]
