# Generated by Django 4.2.3 on 2024-01-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_rename_invoice_purchase_details_invoice_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_details',
            old_name='invoice_id',
            new_name='invoice',
        ),
    ]
