# Generated by Django 4.1.4 on 2023-03-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablecolumn',
            table='functions',
        ),
    ]
