# Generated by Django 4.1.4 on 2023-03-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0003_alter_tablecolumn_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablecolumn',
            table='functions',
        ),
    ]
