# Generated by Django 4.1.4 on 2023-07-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0005_saravanan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saravanan',
        ),
    ]
