# Generated by Django 4.1.4 on 2023-07-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0006_delete_saravanan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablecolumn',
            table='Thamu',
        ),
    ]
