# Generated by Django 4.1.4 on 2023-07-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0007_alter_tablecolumn_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tableColumn',
            new_name='thamu',
        ),
    ]
