# Generated by Django 4.1.4 on 2023-07-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0009_function_delete_thamu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='function',
        ),
    ]
