# Generated by Django 4.1.4 on 2023-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentLogInDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('intime', models.DateTimeField()),
                ('outtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'studentLogInDetails',
            },
        ),
        migrations.CreateModel(
            name='tableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
